name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        shell: bash
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions
          source /opt/ros/humble/setup.bash
          mkdir -p ~/ros2_ws/src
          cp -r . ~/ros2_ws/src/mypkg
          cd ~/ros2_ws/src/mypkg
          bash -x test/test.bash
